restaurant_management/config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:show, :new, :create] do
    resources :order_tables, only: [:new, :create]
  end
  resources :tables, only: [:index]
  resources :menus, only: [:index] 
  resources :order_dishes, only: [:create]
  resources :guests, only: [:new, :create] do
    resources :order_tables, only: [:new, :create]
  end
  resources :order_tables do
    resources :menus, only: [:index]
  end
  resources :reviews, only: [:new, :create, :index]
  namespace :admin do
    resources :staffs
    resources :bills
    resources :categories do
      resources :dishes
    end
    resources :dishes
    resources :menus do
      resources :dishes, only: [:destroy]
    end
  end
end

restaurant_management/app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_dishes
  has_many :dishes, through: :menu_dishes, dependent: :destroy

  scope :search_menu, ->search {where("name LIKE '%#{search}%'").order("id DESC")}

  class << self
    def search search
      search_menu search
    end
  end
end

restaurant_management/app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin, only: [:update, :create, :destroy]
  before_action :find_menu, except: [:index, :new, :create]

  def index
    @menus = if params[:term]
      Menu.search params[:term]
    else
      Menu.all
    end.paginate page: params[:page], per_page: Settings.per_page
  end

  def show
    @menu = Menu.includes(:dishes).find(params[:id])
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new menu_params
    if @menu.save
      flash[:success] = t "flash.menu.create_success"
      redirect_to admin_menus_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @menu.update_attributes menu_params
      flash[:success] = t "flash.menu.update_success"
      redirect_to admin_menu_path @menu
    else
      render :edit
    end
  end

  def destroy
    if @menu.destroy
      flash[:success] =  t "flash.menu.destroy_success"
    else
      flash[:danger] = t "flash.menu.destroy_fail"
    end
    redirect_to admin_menus_path
  end

  private
  def menu_params
    params.require(:menu).permit :name, :description,
      {dish_ids: []}
  end

  def find_menu
    @menu = Menu.find_by id: params[:id]
    unless @menu
      flash[:danger] = t "flash.menu.find_fail"
      redirect_to admin_menus_path
    end
  end
end

restaurant_management/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @dishes = Dish.paginate page: params[:page], per_page: Settings.menu.number_item_in_page
  end
end

restaurant_management/app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

restaurant_management/app/views/admin/menus/_form.html.erb
<%= form_for [:admin, @menu] do |f| %>
  <%= f.label :name, t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description, t(".description") %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.label :dishes, t(".dishes") %>
  <% Dish.all.each do |dish| %>
    <div id="choose">
      <%= check_box_tag "menu[dish_ids][]", dish.id, @menu.dishes.include?(dish) %>
      <%= label_tag :dish_ids, dish.name %>
    </div>
  <% end %>
  <br>
  <% if @menu.new_record? %>
    <%= f.submit t(".create_menu_button"), class: "btn btn-primary" %>
  <% else %>
    <%= f.submit t(".update_menu_button"), class: "btn btn-success" %>
  <% end %>
<% end %>

restaurant_management/app/views/admin/menus/_menu.html.erb
<tr class="dg_tr" id="di_row_0">
  <td class="default_dg_td dg_left dg_nowrap dg1"><%= menu.name %></td>
  <td class="default_dg_td dg_center dg_nowrap">
    <%= link_to t(".view_menu_button"),
      admin_menu_path(menu) %>
  </td>
  <td class="default_dg_td dg_center dg_nowrap">
    <%= link_to t(".edit_menu_button"),
      edit_admin_menu_path(menu) %>
  </td>
  <td class="default_dg_td dg_center dg_nowrap img">
    <%= link_to image_tag("http://icons.iconarchive.com/icons/saki/nuoveXT/128/Actions-button-cancel-icon.png"), admin_menu_path(menu),
      method: :delete, data: {confirm: t(".delete_warning")} %>
  </td>
</tr>

restaurant_management/app/views/admin/menus/edit.html.erb
<section id="new">
<br><br>
  <div class="col-md-8 col-md-offset-2" id="menu">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render "form" %>
  </div>
</section>

restaurant_management/app/views/admin/menus/index.html.erb
<section>
  <br>
  <div class="col-md-8 col-md-offset-2" id="mainarea">
    <h1><%= t ".title" %></h1>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= form_tag admin_menus_path, method: :get, class: "searchform" do %>
      <%= text_field_tag :search, params[:search],
        placeholder: t(".input"), class: "text-input" %>
      <%= submit_tag t(".search"), :name => nil, class: "button" %>
    <% end %>
    <br>
    <table class="default_dg_table">
      <tbody>
        <tr class="dg_tr" style="" id="di_row_">
          <th class="default_dg_th dg_center dg_nowrap dg1"><%= t ".name" %></th>
          <th class="default_dg_th dg_center dg_nowrap dg2" colspan="3">
            <%= t ".opition" %>
          </th>
        </tr>
        <% if @menus.any? %>
          <%= render @menus %>
          <br>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to t(".add_menu_button"), new_admin_menu_path,
      class: "btn btn-primary col-md-2 col-md-offset-5" %>
  </div>
</section>

restaurant_management/app/views/admin/menus/new.html.erb
<section id="new">
<br><br>
  <div class="col-md-8 col-md-offset-2" id="menu">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render "form" %>
  </div>
</section>

restaurant_management/app/views/admin/menus/show.html.erb
<section id="new">
  <h1><%= t ".title" %></h1>
  <div class="col-md-8 col-md-offset-2" id="mainarea">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <table dir="ltr" class="default_dg_table">
      <tbody>
        <tr class="dg_tr" id="di_row_">
          <th class="default_dg_th dg_center dg_nowrap"><b><%= t ".field" %></b></th>
          <th class="default_dg_th dg_center dg_nowrap" colspan="2"><b><%= t ".value" %></b></th>
        </tr>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg_left dg_nowrap"><b><%= t ".name" %></b></td>
          <td class="default_dg_td dg_left"><%= @menu.name %></td>
        </tr>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg_left dg_nowrap"><b><%= t ".description" %></b></td>
          <td class="default_dg_td dg_left" colspan="2"><%= @menu.description %></td>
        </tr>
      </tbody>
    </table>
    <br>
    <h2><%= t ".dishes" %></h2>
    <table dir="ltr" class="default_dg_table">
      <tbody>
        <tr class="dg_tr" style="" id="di_row_">
          <th class="default_dg_th dg_center dg_nowrap" colspan="2"><%= t ".name" %></th>
          <th class="default_dg_th dg_center dg_nowrap">
            <%= t ".category" %>
          </th>
          <th class="default_dg_th dg_center dg_nowrap">
            <%= t ".opition" %>
          </th>
        </tr>
        <% @menu.dishes.each do |f| %>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg_left dg_nowrap" colspan="2"><%= f.name %></td>
          <td class="default_dg_td dg_left dg_nowrap">
            <%= f.category.name %>
          </td>
          <td class="default_dg_td dg_center dg_nowrap">
            <%= link_to t(".delete_dish_button"),
              admin_menu_dish_path(@menu.id, f.id),
              method: :delete, data: {confirm: t(".delete_warning")} %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to t(".edit_menu_button"), edit_admin_menu_path(@menu),
      class: "btn btn-primary col-md-2 col-md-offset-5" %>
  </div>
</section>