restaurant_management/config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:show, :new, :create] do
    resources :order_tables, only: [:new, :create]
  end
  resources :tables, only: [:index]
  resources :menus, only: [:index] 
  resources :order_dishes, only: [:create]
  resources :guests, only: [:new, :create] do
    resources :order_tables, only: [:new, :create]
  end
  resources :order_tables do
    resources :menus, only: [:index]
  end
  resources :reviews, only: [:new, :create, :index]
  namespace :admin do
    resources :staffs
    resources :bills
    resources :categories do
      resources :dishes
    end
    resources :dishes
    resources :menus do
      resources :dishes, only: [:destroy]
    end
  end
end

restaurant_management/app/models/dish.rb
class Dish < ApplicationRecord
  has_many :order_dishes
  has_many :order_tables, through: :order_dishes
  has_many :menu_dishes
  has_many :menus, through: :menu_dishes, dependent: :destroy
  has_many :bill_details
  has_many :bills, through: :bill_detail

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true, numericality: true

  scope :search_dish, ->search {where("name LIKE '%#{search}%'").order("id DESC")}

  class << self
    def search search
      search_dish search
    end
  end
end

restaurant_management/app/controllers/admin/dishes_controller.rb
class Admin::DishesController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin, only: [:update, :create, :destroy]
  before_action :load_category, except: [:index, :show, :destroy]
  before_action :find_category, except: [:index]
  before_action :find_menu_dish, only: [:destroy, :new]
  before_action :find_dish, except: [:index, :new]

  def index
    @dishes = if params[:search]
      Dish.search params[:search]
    else
      Dish.all
    end.paginate page: params[:page]
  end

  def show
  end

  def new
    @dish = Dish.new
  end

  def create
    if @category
      @dish = @category.dishes.build dish_params
      if @dish.save
        flash[:success] = t "flash.dish.create_success"
        redirect_to admin_category_path @category
      end
    else
      @dish = Dish.new dish_params
      if @dish.save
        flash[:success] = t "flash.dish.create_success"
        redirect_to admin_dishes_path
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    @dish.category_id = params[:category_id]
    if @dish.update_attributes dish_params
      flash[:success] = t "flash.dish.update_success"
      if @category
        redirect_to admin_category_path @category
      else
        redirect_to admin_dishes_path
      end
    else
      render :edit
    end
  end

  def destroy
    if @menu
      @menu.dishes.include?(@dish)
      if @menu.dishes.delete @dish
        redirect_to admin_menu_path @menu
      end
    else
      if @dish.destroy
        flash[:success] = t "flash.dish.destroy_success"
      else
        flash[:danger] = t "flash.dish.destroy_fail"
      end
      if @category
        redirect_to admin_category_path @category
      else
        redirect_to admin_dishes_path
      end
    end
  end

  private
  def dish_params
    params.require(:dish).permit :name, :price, :description, :category_id
  end

  def find_category
    @category = Category.find_by id: params[:category_id]
    unless @category
      # flash[:danger] = t "flash.category.find_fail"
    end
  end

  def find_dish
    @dish = if @category
      @category.dishes.find_by id: params[:id]
    else
      Dish.find_by id: params[:id]
    end
    unless @dish
      # flash[:danger] = t "flash.dish.find_fail"
    end
  end

  def find_menu_dish
    @menu = Menu.find_by id: params[:menu_id]
    unless @menu
      # flash[:danger] = t "flash.menu.find_fail"
    end
    @dish = Dish.find_by id: params[:id]
    unless @dish
      # flash[:danger] = t "flash.dish.find_fail"
    end
  end

  def load_category
    @categories = Category.all.map {|p| [p.name, p.id]}
  end
end

restaurant_management/app/views/admin/dishes/_dish.html.erb
<% if @category %>
  <li>
    <div class="title_holder">
      <%= dish.name %>
    </div>
    <div class="view_holder">
      <%= link_to t("button.view"),
        admin_category_dish_path(dish.category_id, dish) %>
    </div>
    <div class="edit_holder">
      <%= link_to t("button.edit"),
        edit_admin_category_dish_path(dish.category_id, dish) %>
    </div>
    <div class="delete_holder">
      <%= link_to t("button.delete"),
        admin_category_dish_path(dish.category_id, dish), method: :delete,
        data: {confirm: t(".delete_warning")} %>
    </div>
  </li>
<% else %>
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg_left dg_nowrap"><%= dish.name %></td>
    <td class="default_dg_td dg_left dg_nowrap">
      <%= dish.category.name %>
    </td>
    <td class="default_dg_td dg_left dg_nowrap">
      <%= t ".money" %><%= dish.price %>
    </td>
    <td class="default_dg_td dg_center dg_nowrap">
      <%= link_to t(".view_dish_button"),
        admin_dish_path(dish) %>
    </td>
    <td class="default_dg_td dg_center dg_nowrap">
      <%= link_to t(".edit_dish_button"),
        edit_admin_dish_path(dish) %>
    </td>
    <td class="default_dg_td dg_center dg_nowrap">
      <%= link_to image_tag("http://icons.iconarchive.com/icons/saki/nuoveXT/128/Actions-button-cancel-icon.png"), admin_dish_path(dish),
        method: :delete, data: {confirm: t(".delete_warning")} %>
    </td>
  </tr>
<% end %>

restaurant_management/app/views/admin/dishes/_form.html.erb
<%= form_for [:admin, @category, @dish] do |f| %>
  <%= f.label :name, t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :price, t(".price") %>
  <%= f.text_field :price, class: "form-control" %>

  <%= f.label :description, t(".description") %>
  <%= f.text_area :description, class: "form-control" %>

  <% unless @category %>
    <%= f.label :category_id, t(".category") %>
    <%= f.select :category_id, @categories, include_blank: false,
      selected: :category_id, class: "form-control" %>
  <% end %>

  <% if @dish.new_record? %>
    <%= f.submit t("button.add"), class: "btn btn-primary" %>
  <% else %>
    <%= f.submit t("button.update"), class: "btn btn-success" %>
  <% end %>
<% end %>

restaurant_management/app/views/admin/dishes/edit.html.erb
<section>
  <div id="edit" class="col-sm-6">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render "form" %>
  </div>
</section>

restaurant_management/app/views/admin/dishes/index.html.erb
<section>
  <br>
  <div class="col-md-8 col-md-offset-2" id="mainarea">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <h1><%= t ".title" %></h1>
    <%= form_tag admin_dishes_path, method: :get, class: "searchform" do %>
      <%= text_field_tag :search, params[:search],
        placeholder: t(".input"), class: "text-input" %>
      <%= submit_tag t(".search"), :name => nil, class: "button" %>
    <% end %>
    <div class="clearfix"></div>
    <% if @dishes.blank? %>
      <h4><%= t ".search_fail" %><%= params[:search] %></h4>
    <% end %>
    <table class="default_dg_table">
      <tbody>
        <tr class="dg_tr" style="" id="di_row_">
          <th class="default_dg_th dg_center dg_nowrap"><%= t ".name" %></th>
          <th class="default_dg_th dg_center dg_nowrap">
            <%= t ".category" %>
          </th>
          <th class="default_dg_th dg_center dg_nowrap"><%= t ".price" %></th>
          <th class="default_dg_th dg_center dg_nowrap" colspan="3">
            <%= t ".opition" %>
          </th>
        </tr>
        <% if @dishes.any? %>
          <%= render @dishes %>
          <br>
          <%= will_paginate @dishes %>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to t(".add_dish_button"), new_admin_dish_path,
      class: "btn btn-primary col-md-offset-5" %>
  </div>
</section>

restaurant_management/app/views/admin/dishes/new.html.erb
<section>
  <div id="edit" class="col-sm-6">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render "form" %>
  </div>
</section>

restaurant_management/app/views/admin/dishes/show.html.erb
<section id="new">
  <h1><%= t ".title" %></h1>
  <div class="col-md-8 col-md-offset-2">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <table dir="ltr" class="default_dg_table">
      <tbody>
        <tr class="dg_tr" id="di_row_">
          <th class="default_dg_th dg_center dg_nowrap"><b><%= t ".field" %></b></th>
          <th class="default_dg_th dg_center dg_nowrap"><b><%= t ".value" %></b></th>
        </tr>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg_left dg_nowrap"><b><%= t ".category" %></b></td>
          <td class="default_dg_td dg_left"><%= @dish.category.name %></td>
        </tr>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg_left dg_nowrap"><b><%= t ".name" %></b></td>
          <td class="default_dg_td dg_left"><%= @dish.name %></td>
        </tr>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg_left dg_nowrap"><b><%= t ".description" %></b></td>
          <td class="default_dg_td dg_left"><%= @dish.description %></td>
        </tr>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg_left dg_nowrap"><b><%= t ".price" %></b></td>
          <td class="default_dg_td dg_left"><%= t ".money" %><%= @dish.price %></td>
        </tr>
      </tbody>
    </table>
  </div>
</section>