restaurant_management/config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:show, :new, :create] do
    resources :order_tables, only: [:new, :create]
  end
  resources :tables, only: [:index]
  resources :menus, only: [:index] 
  resources :order_dishes, only: [:create]
  resources :guests, only: [:new, :create] do
    resources :order_tables, only: [:new, :create]
  end
  resources :order_tables do
    resources :menus, only: [:index]
  end
  resources :reviews, only: [:new, :create, :index]
  namespace :admin do
    resources :staffs
    resources :bills
    resources :categories do
      resources :dishes
    end
    resources :dishes
    resources :menus do
      resources :dishes, only: [:destroy]
    end
  end
end

restaurant_management/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

restaurant_management/app/models/bill.rb
class Bill < ApplicationRecord
  has_many :bill_details
  has_many :dishes, through: :bill_details

  belongs_to :staff
  belongs_to :target, polymorphic: true
  accepts_nested_attributes_for :bill_details, :allow_destroy => true
end

restaurant_management/app/models/bill_detail.rb
class BillDetail < ApplicationRecord
  belongs_to :bill, optional: true
  belongs_to :dish
end

restaurant_management/app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes, dependent: :destroy

  validates :name, presence: true

  scope :search_category, ->search {where("name LIKE '%#{search}%'").order("id DESC")}

  class << self
    def search search
      search_category search
    end
  end
end

restaurant_management/app/models/dish.rb
class Dish < ApplicationRecord
  has_many :order_dishes
  has_many :order_tables, through: :order_dishes
  has_many :menu_dishes
  has_many :menus, through: :menu_dishes, dependent: :destroy
  has_many :bill_details
  has_many :bills, through: :bill_detail

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true, numericality: true

  scope :search_dish, ->search {where("name LIKE '%#{search}%'").order("id DESC")}

  class << self
    def search search
      search_dish search
    end
  end
end

restaurant_management/app/models/guest.rb
class Guest < ApplicationRecord
  has_many :order_tables, as: :target
  has_one :review, as: :target
  has_many :bills, as: :target

  before_save :downcase_email

  validates :name, presence: true, length: {maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}

  validates :phone, presence: true, numericality: true,
    length: {minimum: Settings.phone_number.min_length, 
      maximum: Settings.phone_number.max_length}

  accepts_nested_attributes_for :review

  private
  def downcase_email
    self.email = email.downcase
  end
end

restaurant_management/app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_dishes
  has_many :dishes, through: :menu_dishes, dependent: :destroy

  scope :search_menu, ->search {where("name LIKE '%#{search}%'").order("id DESC")}

  class << self
    def search search
      search_menu search
    end
  end
end

restaurant_management/app/models/menu_dish.rb
class MenuDish < ApplicationRecord
  belongs_to :menu
  belongs_to :dish
end

restaurant_management/app/models/order_dish.rb
class OrderDish < ApplicationRecord
  belongs_to :order_table
  belongs_to :dish

  validates :quantity, presence: true, numericality: {greater_than_or_equal_to: 1}
end

restaurant_management/app/models/order_table.rb
class OrderTable < ApplicationRecord
  has_many :order_dishes
  has_many :dishes, through: :order_dishes

  belongs_to :table
  belongs_to :target, polymorphic: true

  attr_accessor :day 

  scope :book_in_about, -> from, to {
    where "(book_from BETWEEN ? AND ?) or (book_to BETWEEN ? AND ?)" ,from ,to, from ,to
  }
end

restaurant_management/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :target, polymorphic: true, optional: true

  validates :content, presence: true, length: {maximum: 1000}

  scope :order_desc, -> {order created_at: :desc}
end

restaurant_management/app/models/role.rb
class Role < ApplicationRecord
  has_many :staffs
end

restaurant_management/app/models/staff.rb
class Staff < ApplicationRecord
  has_many :bills
  
  belongs_to :role
end

restaurant_management/app/models/table.rb
class Table < ApplicationRecord
  has_many :order_tables

  scope :free, -> (capacity, from, to) {
    list_booked = OrderTable.book_in_about(from ,to).map(&:table_id)
    if list_booked.count == 0
    	list_booked = [0]
    end
    where("capacity = (?) AND id not in (?)",capacity ,list_booked)
  }
end

restaurant_management/app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email

  has_many :order_tables, as: :target
  has_many :reviews, as: :target
  has_many :bills, as: :target

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  has_secure_password

  private
  def downcase_email
    self.email = email.downcase
  end
end

restaurant_management/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @dishes = Dish.paginate page: params[:page], per_page: Settings.menu.number_item_in_page
  end
end

restaurant_management/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_page?
    File.exist? Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb")
  end
end

restaurant_management/app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    if params[:table]
      from = params[:table][:day] + " " + params[:table][:from]
      to = params[:table][:day] + " " + params[:table][:to]
      @tables = Table.free params[:table][:capacity], from, to
    end
  end
end

restaurant_management/app/helpers/application_helper.rb
module ApplicationHelper
end

restaurant_management/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

restaurant_management/app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

restaurant_management/app/views/tables/_form.html.erb
<%= form_for :table, url: tables_path, method: :get do |f| %>
  <div class="col-sm-12 dropdown-buttons">
    <div class="details-1">
      <div class="col-sm-12">
        <p>
          <% if @tables %>
            <% unless @tables.any? %>
              <%= t "order_table.index.not_found" %>
            <% else %>
              <%= t "order_table.index.found_out" %>
              <%= @tables.count.to_s %>
              <%= t "order_table.index.tables" %>
              <% @tables.each do |table| %>
                <%= t "order_table.index.table" %>
                <%= table.id.to_s %>
              <% end %>
            <% end %>
          <% end %>
        </p>
      </div>
      <div class="col-sm-12 dropdown-buttons"> 
        <div class="col-sm-3 dropdown-button">
          <div class="input-group">
            <%= f.date_field :day ,value: Date.today, class: "form-control has-dark-background" %>
          </div>
        </div>
        <div class="col-sm-2 dropdown-button">
          <div class="input-group">
            <%= f.number_field :capacity, min: Settings.capacity.minimum_value, 
              max: Settings.capacity.maximum_value, class: "form-control has-dark-background", 
              placeholder: (t "order_table.index.capacity") %>
          </div>
        </div>
        <div class="col-sm-2 dropdown-button">
          <div class="input-group">
            <%= f.time_field :from, class: "form-control has-dark-background",
              placeholder: (t "order_table.index.from") %>
          </div>
        </div>
        <div class="col-sm-2 dropdown-button"> 
          <div class="input-group">
            <%= f.time_field :to, class: "form-control has-dark-background",
              placeholder: (t "order_table.index.to") %>
          </div>
        </div>
        <div class="col-sm-2 submit_button"> 
          <div class="input-group">
            <%= f.submit t "order_table.index.find_tables" %>
          </div>
        </div>
        <div class="col-sm-1 submit_button"> 
          <div class="input-group">
            <% if current_user %>
              <%= link_to t("order_table.index.go_book_table"), new_user_order_table_path(current_user),
                class: "btn2" %>
            <% else %>
              <%= link_to t("order_table.index.go_book_table"), new_guest_path, class: "btn2" %>
            <% end %>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div> 
      <div class="clearfix"> </div>
    </div>
  </div>
<% end %>

restaurant_management/app/views/tables/index.html.erb
<section id="home" class="parallax-section">
  <div class="container-fluid">
    <div class="banner-info">
      <%= render "form" %>
    </div>
    <div>
      <%= image_tag("table-scheme.png", alt: "rss feed", class: "image") %>
    </div>
  </div>
</section>