restaurant_management/config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:show, :new, :create] do
    resources :order_tables, only: [:new, :create]
  end
  resources :tables, only: [:index]
  resources :menus, only: [:index] 
  resources :order_dishes, only: [:create]
  resources :guests, only: [:new, :create] do
    resources :order_tables, only: [:new, :create]
  end
  resources :order_tables do
    resources :menus, only: [:index]
  end
  resources :reviews, only: [:new, :create, :index]
  namespace :admin do
    resources :staffs
    resources :bills
    resources :categories do
      resources :dishes
    end
    resources :dishes
    resources :menus do
      resources :dishes, only: [:destroy]
    end
  end
end

restaurant_management/app/models/staff.rb
class Staff < ApplicationRecord
  has_many :bills
  
  belongs_to :role
end

restaurant_management/app/controllers/admin/staffs_controller.rb
class Admin::StaffsController < ApplicationController
  before_action :verify_admin, only: [:update, :create, :destroy]
  before_action :find_staff, except: [:index, :new, :create]
  before_action :load_role, only: [:new, :edit]

  def index
    @staffs = Staff.paginate page: params[:page], per_page: Settings.page.max[1]
  end

  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.new staff_params
    if @staff.save
      flash[:success] = t "flash.new_staff"
      StaffMailer.staff_email(@staff).deliver
      redirect_to admin_staffs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @staff.update_attributes staff_params
      flash[:success] = t "dialog.success"
      redirect_to admin_staffs_path
    else
      flash[:danger] = t "dialog.fail"
      render :edit
    end
  end

  def destroy
    @staff.destroy
    redirect_to :back
  end

  private
  def find_staff
    @staff = Staff.find_by id: params[:id]
    unless @staff
      flash[:danger] = t "flash.staff"
      redirect_to :back
    end
  end

  def staff_params
    params.require(:staff).permit :name, :email, :salary,
      :work_days, :role_id
  end

  def load_role
    @role = Role.all.collect { |p| [ p.name, p.id ] }
  end
end

restaurant_management/app/views/admin/staffs/_form.html.erb
<%= form_for [:admin, @staff]  do |f| %>
  <%= render "shared/error_messages", object: @staff %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control",
    value: @staff.name, placeholder: t("admin.staff_name_input") %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control",
    value: @staff.email, placeholder: t("admin.staff_email_input") %>

  <%= f.label :salary %>
  <%= f.number_field :salary, class: "form-control",
    value: @staff.salary, placeholder: t("admin.staff_salary_input") %>

  <%= f.label :work_days %>
  <%= f.number_field :work_days, class: "form-control",
    value: @staff.work_days, placeholder: t("admin.staff_work_days_input") %>

  <%= f.label :role_id %>
  <%= f.select :role_id, @role, include_blank: false,
    selected: @staff.role_id %>

  <%= f.submit t("flash.update_staff"), class: "btn btn-primary" %>
<% end %>

restaurant_management/app/views/admin/staffs/_staff.html.erb
<tr>
  <td><%= link_to staff.name, edit_admin_staff_path(staff) %></td>
  <td><%= staff.email %></td>
  <td><%= staff.salary %></td>
  <td><%= staff.work_days %></td>
  <td><%= staff.role.name %></td>
  <td><%= link_to t("staff.del"), admin_staff_path(staff),
    method: :delete, id: "btn", class: "btn",
    data: {confirm: t("dialog.confirm_delete")} %></td>
</tr>

restaurant_management/app/views/admin/staffs/edit.html.erb
<% provide :title, t("admin.staff.edit") %>
<section class="center-block">
  <h1 class="text-center"><%= t "admin.staff" %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
    </div>
  </div>
</section>

restaurant_management/app/views/admin/staffs/index.html.erb
<section>
  <div class="container">
    <div class="btn" id="add_btn">
      <%= link_to t("admin.staff_add"), new_admin_staff_path %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th class="col-md-1"><%= t "staff.name" %></th>
          <th class="col-md-1"><%= t "staff.email" %></th>
          <th class="col-md-1"><%= t "staff.salary" %></th>
          <th class="col-md-1"><%= t "staff.workday" %></th>
          <th class="col-md-1"><%= t "staff.role" %></th>
          <th class="col-md-1"><%= t "staff.action" %></th>
        </tr>
      </thead>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <tbody>
        <%= render @staffs %>
        <%= will_paginate @staffs%>
      </tbody>
    </table>
  </div>
</section>

restaurant_management/app/views/admin/staffs/new.html.erb
<% provide :title, t("admin.staff_add") %>
<section class="center-block">
  <h1 class="text-center"><%= t "admin.staff_add" %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
    </div>
  </div>
</section>